### ISSUE TITLE
Infinite loop with multiple=true 

### ISSUE THREAD

**Issue by MojoJojo** [cibernox/ember-power-select#134]
Hi,
I'm using ember-power-select in my project (Ember 1.13.0, Ember Data 1.0.0-beta.18) and have the following config:

Template: 
```
{{#power-select options=model.accomodationTypes selected=selectedAccomodationTypes multiple=true onchange=(action (mut selectedAccomodationTypes)) as |accType|}}
     <span>{{accType.text}}</span>
{{/power-select}}
```
Data is loaded in the model hook using Ember Data store.find() and selectedAccomodationTypes is variable defined in the controller. When the page is rendered, all the data is loaded/displayed properly and I chose the first option. However, when I try and select the second option, it seems like something goes in an infinite loop and I get the following messages in console until I kill the browser window:

```
2015-11-18 00:30:54.912 ember.debug.js:5442 DEPRECATION: You modified (no label) twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 2.0
        at _emberViewsViewsCore_view.default.extend.scheduleRevalidate (http://localhost:4200/assets/vendor.js:58967:35)
        at http://localhost:4200/assets/vendor.js:21808:32
        at Object.Stream.notifySubscribers (http://localhost:4200/assets/vendor.js:31107:11)
        at Object.Stream.notifyExcept (http://localhost:4200/assets/vendor.js:31047:14)
        at Object.Stream.notify (http://localhost:4200/assets/vendor.js:31041:12)
        at Object.Stream.notifySubscribers (http://localhost:4200/assets/vendor.js:31109:20)
        at Object.Stream.notifyExcept (http://localhost:4200/assets/vendor.js:31047:14)
        at Object.Stream.notify (http://localhost:4200/assets/vendor.js:31041:12)
        at Object.bindLocal (http://localhost:4200/assets/vendor.js:18015:16)
2015-11-18 00:30:54.913 ember.debug.js:5341 WARNING: Using `{{each}}` without specifying a key can lead to unusual behavior.  Please specify a `key` that identifies a unique value on each item being iterated. E.g. `{{each model key="@guid" as |item|}}`.
2015-11-18 00:30:54.925 ember.debug.js:5442 DEPRECATION: You modified (no label) twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 2.0
        at _emberViewsViewsCore_view.default.extend.scheduleRevalidate (http://localhost:4200/assets/vendor.js:58967:35)
        at http://localhost:4200/assets/vendor.js:21808:32
        at Object.Stream.notifySubscribers (http://localhost:4200/assets/vendor.js:31107:11)
        at Object.Stream.notifyExcept (http://localhost:4200/assets/vendor.js:31047:14)
        at Object.Stream.notify (http://localhost:4200/assets/vendor.js:31041:12)
        at Object.Stream.notifySubscribers (http://localhost:4200/assets/vendor.js:31109:20)
        at Object.Stream.notifyExcept (http://localhost:4200/assets/vendor.js:31047:14)
        at Object.Stream.notify (http://localhost:4200/assets/vendor.js:31041:12)
        at Object.bindLocal (http://localhost:4200/assets/vendor.js:18015:16)
2015-11-18 00:30:54.926 ember.debug.js:5442 DEPRECATION: You modified opt twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 2.0
        at _emberViewsViewsCore_view.default.extend.scheduleRevalidate (http://localhost:4200/assets/vendor.js:58967:35)
        at http://localhost:4200/assets/vendor.js:21808:32
        at Object.Stream.notifySubscribers (http://localhost:4200/assets/vendor.js:31107:11)
        at Object.Stream.notifyExcept (http://localhost:4200/assets/vendor.js:31047:14)
        at Object.Stream.notify (http://localhost:4200/assets/vendor.js:31041:12)
        at Object.bindLocal (http://localhost:4200/assets/vendor.js:18015:16)
        at Object.updateLocal (http://localhost:4200/assets/vendor.js:60020:15)
        at RenderResult.updateLocals (http://localhost:4200/assets/vendor.js:61037:22)
        at RenderResult.revalidateWith (http://localhost:4200/assets/vendor.js:60959:12)
2015-11-18 00:30:54.928 ember.debug.js:5442 DEPRECATION: You modified opt twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 2.0
        at _emberViewsViewsCore_view.default.extend.scheduleRevalidate (http://localhost:4200/assets/vendor.js:58967:35)
        at http://localhost:4200/assets/vendor.js:21808:32
        at Object.Stream.notifySubscribers (http://localhost:4200/assets/vendor.js:31107:11)
        at Object.Stream.notifyExcept (http://localhost:4200/assets/vendor.js:31047:14)
        at Object.Stream.notify (http://localhost:4200/assets/vendor.js:31041:12)
        at Object.bindLocal (http://localhost:4200/assets/vendor.js:18015:16)
        at Object.updateLocal (http://localhost:4200/assets/vendor.js:60020:15)
        at RenderResult.updateLocals (http://localhost:4200/assets/vendor.js:61037:22)
        at RenderResult.revalidateWith (http://localhost:4200/assets/vendor.js:60959:12)
2015-11-18 00:30:54.929 ember.debug.js:5442 DEPRECATION: You modified opt twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 2.0
        at _emberViewsViewsCore_view.default.extend.scheduleRevalidate (http://localhost:4200/assets/vendor.js:58967:35)
        at http://localhost:4200/assets/vendor.js:21808:32
        at Object.Stream.notifySubscribers (http://localhost:4200/assets/vendor.js:31107:11)
        at Object.Stream.notifyExcept (http://localhost:4200/assets/vendor.js:31047:14)
        at Object.Stream.notify (http://localhost:4200/assets/vendor.js:31041:12)
        at Object.bindLocal (http://localhost:4200/assets/vendor.js:18015:16)
        at Object.updateLocal (http://localhost:4200/assets/vendor.js:60020:15)
        at RenderResult.updateLocals (http://localhost:4200/assets/vendor.js:61037:22)
        at RenderResult.revalidateWith (http://localhost:4200/assets/vendor.js:60959:12)
2015-11-18 00:30:54.931 ember.debug.js:5442 DEPRECATION: You modified opt.text twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 2.0
```
Not sure what is going on here?

**Comment by MojoJojo** [comment]
Okay, seems like an Ember 1.13.0 issue. Upgrading to 1.13.11 fixed it for me.
