### ISSUE TITLE
Deployed docs site gives 404s when using direct links or refreshing

### ISSUE THREAD

**Issue by gvdp** [cibernox/ember-power-select#1496]
The docs site works when you go to the root and then navigate, but not when you refresh the page or use a direct link like https://ember-power-select.com/docs.

Probably caused by the Netlify settings, because it's a single page app it should redirect all routes to the root:
https://guides.emberjs.com/v4.1.0/getting-started/quick-start/#toc_deploying-your-app-to-netlify
https://www.netlify.com/blog/2020/04/07/creating-better-more-predictable-redirect-rules-for-spas/

**Comment by k3n** [comment]
Examples don't work regardless (both Chrome & Firefox):

```
vendor-ed69449c76b340fba8baa47ccd32387d.js:2292 

Uncaught (in promise) TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at u.helper (vendor-ed69449c76b340fba8baa47ccd32387d.js:2292:47)
    at vendor-ed69449c76b340fba8baa47ccd32387d.js:2222:5
    at ne (vendor-ed69449c76b340fba8baa47ccd32387d.js:2222:20)
    at l (vendor-ed69449c76b340fba8baa47ccd32387d.js:2195:1)
    at vendor-ed69449c76b340fba8baa47ccd32387d.js:2177:6
    at _.compile (vendor-ed69449c76b340fba8baa47ccd32387d.js:2107:173)
    at te (vendor-ed69449c76b340fba8baa47ccd32387d.js:2195:44)
    at vendor-ed69449c76b340fba8baa47ccd32387d.js:2191:30
    at J.compile (vendor-ed69449c76b340fba8baa47ccd32387d.js:2192:23)
```

**Comment by mkszepp** [comment]
Old issue, but i want to inform that this was fixed in latest version
