### ISSUE TITLE
Cannot read property 'userAgent' of undefined on FastBoot

### ISSUE THREAD

**Issue by josemarluedke** [cibernox/ember-power-select#529]
Hi there! 

I encountered a problem using the power-select with Ember FastBoot. 

```
There was an error running your app in fastboot. More info about the error:
 TypeError: Cannot read property 'userAgent' of undefined
    at Module.callback (/Users/josemarluedke/Projects/manager/dist/fastboot/vendor.js:88373:47)
    at Module.exports (/Users/josemarluedke/Projects/manager/dist/fastboot/vendor.js:119:34)
    at Module.build (/Users/josemarluedke/Projects/manager/dist/fastboot/vendor.js:174:10)
    at findModule (/Users/josemarluedke/Projects/manager/dist/fastboot/vendor.js:223:9)
    at Module.reify (/Users/josemarluedke/Projects/manager/dist/fastboot/vendor.js:151:22)
    at Module.build (/Users/josemarluedke/Projects/manager/dist/fastboot/vendor.js:173:10)
    at findModule (/Users/josemarluedke/Projects/manager/dist/fastboot/vendor.js:223:9)
    at requireModule (/Users/josemarluedke/Projects/manager/dist/fastboot/vendor.js:26:12)
    at [object Object]._extractDefaultExport (/Users/josemarluedke/Projects/manager/dist/fastboot/vendor.js:92577:20)
    at [object Object].resolveOther (/Users/josemarluedke/Projects/manager/dist/fastboot/vendor.js:92312:32)
    at [object Object].superWrapper (/Users/josemarluedke/Projects/manager/dist/fastboot/vendor.js:32386:22)
    at [object Object].exports.default._emberRuntimeSystemObject.default.extend.resolve (/Users/josemarluedke/Projects/manager/dist/fastboot/vendor.js:16075:35)
    at resolve (/Users/josemarluedke/Projects/manager/dist/fastboot/vendor.js:12553:36)
    at Object.Registry.resolve (/Users/josemarluedke/Projects/manager/dist/fastboot/vendor.js:12014:21)
    at Object.Registry.resolve (/Users/josemarluedke/Projects/manager/dist/fastboot/vendor.js:12018:55)
    at factoryFor (/Users/josemarluedke/Projects/manager/dist/fastboot/vendor.js:11509:28)
    at Object.Container.lookupFactory (/Users/josemarluedke/Projects/manager/dist/fastboot/vendor.js:11375:14)
    at [object Object].exports.default._emberMetalMixin.Mixin.create._lookupFactory (/Users/josemarluedke/Projects/manager/dist/fastboot/vendor.js:42750:33)
    at [object Object].exports.default._emberRuntimeSystemObject.default.extend.componentFor (/Users/josemarluedke/Projects/manager/dist/fastboot/vendor.js:50757:2

```

I suspect that the problem is coming from https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select-multiple/trigger.js#L7.

**Comment by josemarluedke** [comment]
Hey @cibernox, any ideas how can I fix this problem? I'm open to work fixing this problem, I just need some guidance.

**Comment by cibernox** [comment]
Hey. Sorry, I forgot to answer to this in the very moment and then it felt into oblivion. I think that it shouldn't be hard to fix. Probably is this line: https://github.com/cibernox/ember-power-select/blob/67e1c631356f30b0f2dbe74b4346e340f5b4ddb7/addon/components/power-select-multiple/trigger.js#L14

Basically the component should not attempt to access the navigator if it's not running in an browser.
