### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by sibijohn72** [cibernox/ember-power-select#802]
Hi, i just did a fresh install of ember-power-select and i am getting this error. 

`C:\setup\ember\project-cronus\node_modules\ember-power-select\index.js:7
  included(appOrAddon) {
          ^
Unexpected token (
SyntaxError: Unexpected token (
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Function.Addon.lookup (C:\setup\ember\project-cronus\node_modules\ember-cli\lib\models\addon.js:998:19)
    at C:\setup\ember\project-cronus\node_modules\ember-cli\lib\models\addons-factory.js:48:38
    at visit (C:\setup\ember\project-cronus\node_modules\ember-cli\lib\utilities\DAG.js:23:3)
    at visit (C:\setup\ember\project-cronus\node_modules\ember-cli\lib\utilities\DAG.js:21:5)
    at visit (C:\setup\ember\project-cronus\node_modules\ember-cli\lib\utilities\DAG.js:21:5)
`

**Comment by cibernox** [comment]
My guess is that you are using an ancient version of node.js that doesn't support ES6 syntax. 
This addon removes support for versions of node as soon as they enter End Of Life.

**Comment by cibernox** [comment]
I'm closing this, let me know if that was the reason.
